### ISSUE TITLE
здравствуйте как вам идея м

### ISSUE THREAD

**Issue by nitreojs** [tangenx/lfdi#1]
## здравствуйте как вам идея м
здравствуйте как вам идея м

**Comment by evtn** [comment]
გამარჯობა
поддерживаю

**Comment by tangenx** [comment]
хорошая идея, спасибо!

**Comment by bit0r1n** [comment]
самый адекватный политик

**Comment by tailsjs** [comment]
пожалуй, соглашусь. лучшая идея за последние 1000 лет
