### ISSUE TITLE
здравствуйте спасибо за то что исправили баг!!!

### ISSUE THREAD

**Issue by tailsjs** [tangenx/lfdi#13]
здравствуйте спасибо за то что исправили баг когда ел сухарики хрустим со сметаной и зеленью то приложение вылетало стало лучше но у меня баг когда снимаешь носки то lfdi превращяется в кириешки со вкусом сыра и захватывает украину пофиксите пж носки у меня хлопковые на 101%

**Comment by tangenx** [comment]
ок

**Comment by tailsjs** [comment]
фухххх спс что и этот баг исправили спасибо спасибо я за вас свечку поставлю
