### ISSUE TITLE
wher mac

### ISSUE THREAD

**Issue by m4l3vich** [tangenx/lfdi#2]
henlo hawaryu im under de wotar
i use maki osi ekes ekes ekes ekes pls make build

![me](https://i.imgur.com/llGAzZB.png)
plis help mi

**Comment by tangenx** [comment]
MacOS builds coming soon!

**Comment by m4l3vich** [comment]
y u close issue pls write here when maki osi builde is avalabel
saparakaraib to my issue to know when maki osi program release😃
