### ISSUE TITLE
False Invalid Discord Token 

### ISSUE THREAD

**Issue by TsunamiHD** [tangenx/lfdi#8]
Hi,
So everytime i enter all my Details it tells my my Discord Token is invalid but it actually isnt. If i just disregard the error and apply the settings it works just fine for a few Minutes but then it deletes all the Info from the Discord Gateaway settings Tab. So it says it's wrong, then it works and then it stops working after like 2 Songs. I've tried both the Installed and Portable Version on the Newest Release and if it works it's working great. Oh while writing this it actually started working again without me doing anything, the applied settings didn't return though. Maybe it actually solved itself but you might want to look into it because yesterday it didn't work at all.

**Comment by tangenx** [comment]
Thank you for describing the issue in detail! I will check it out.

If the problem repeats, there may be corresponding errors in the Log Console. Please take a screenshot of the Log Console or copy them as text and post it here **(erase your Discord token if you have one!)**

**Comment by TsunamiHD** [comment]
> (20:25:09) [RPC] No playing tracks now, abort.
(20:25:38) [RPC] Start updating track...
(20:25:39) [RPC] No playing tracks now, abort.
(20:26:08) [RPC] Start updating track...
(20:26:09) [RPC] No playing tracks now, abort.
(20:26:38) [RPC] Start updating track...
(20:26:39) [RPC] No playing tracks now, abort.
(20:27:08) [RPC] Start updating track...
(20:27:09) [RPC] No playing tracks now, abort.
(20:27:38) [RPC] Start updating track...
(20:27:39) [RPC] No playing tracks now, abort.
(20:28:08) [RPC] Start updating track...
(20:28:09) [RPC] No playing tracks now, abort.
(20:28:38) [RPC] Start updating track...
(20:28:39) [RPC] No playing tracks now, abort.
(20:29:08) [RPC] Start updating track...
(20:29:09) [RPC] No playing tracks now, abort.
(20:29:38) [RPC] Start updating track...
(20:29:39) [RPC] No playing tracks now, abort.
(20:30:08) [RPC] Start updating track...

This is the log console, I was listening to Music and it was being scrobbeled to last.fm. I made sure to listen to multiple songs and it didn't change anything. Is this enough, this is the first time I've reported an issue if you need anything else I can send it aswell.

**Comment by tangenx** [comment]
Perhaps the music app is not connected to last.fm, or it's not sending last.fm a "Scrobbling Now" status. I can't help you with the second one, but check your music app settings just in case.

**Comment by Klaex** [comment]
Same here, when I add the value from "authentication" it simply says it's invalid

**Comment by Klaex** [comment]
```
(15:56:39) [RPC] Triggered init
(15:56:39) [RPC] Initializing...
(15:56:39) [RPC] Initialize complete
(15:56:39) [RPC] Triggered start
(15:56:39) [RPC] Starting..
(15:56:39) Border size: 1.0
(15:57:09) [RPC] Start updating track...
(15:57:09) [RPC] Track updated
```

Seems like it's not even trying to connect to Spotify since it thinks the token is invalid. If I remove some of the last characters it seems to think it's valid but later finds out it's an invalid token anyway :^)

```
(15:59:00) [DWS: Manager] Triggered init
(15:59:00) [DWS: Manager] Start init
(15:59:00) [DWS: Main] Creating connection
(15:59:00) [DWS: Main] Starting listen to events
(15:59:00) [DWS: Manager] Successfully initialized
(15:59:00) [DWS: Main] New message.
(15:59:00) [DWS: WSMessageHandler] Message info: OP Code is 10 (Hello). 
(15:59:00) [DWS: WSMessageHandler]  Selected handler: Instance of 'HelloHandler'
(15:59:00) [DWS: HelloHandler] Received timer setup command.
(15:59:00) [DWS: WSMessageHandler] Handler returns data: {"operationCode":10,"error":null,"data":{"success":true,"configureHeartbeat":true}}
(15:59:00) [DWS: WSMessageHandler] Setup heartbeat timer.
(15:59:01) [DWS: Manager sendIdentify] Triggered.
(15:59:01) [DWS: Manager sendIdentify] Sending identify.
(15:59:01) [DWS: Main] Sending message: {"op":2,"d":{"token":"---","properties":{"$os":"windows","$browser":"discord.js","$device":"discord.js","$referrer":"","$referring_domain":""},"large_threshold":250,"compress":true,"version":6},"s":null,"t":null}
(15:59:01) [DWS: Main] WebSocket connection was closed.
(15:59:01) [DWS: Main] WebSocket close code: 4004
(15:59:01) [DWS: Manager onClose_Manager] Triggered.
(15:59:01) [DWS: Manager] Triggered stopUpdating.
(15:59:01) [DWS: Manager] updatePresenceTimer state: null.
(15:59:04) [DWS: Manager] Triggered dispose
(15:59:04) [DWS: Main] Triggered dispose
(15:59:04) [DWS: Main] Closing connection
```

**Comment by tangenx** [comment]
Referring to the [Gateway documentation](https://github.com/meew0/discord-api-docs-1/blob/master/docs/topics/GATEWAY.md#disconnections), error code 4004 means the wrong token. 

Strange. Perhaps, the problem is in the Discord token retrieving guide.

Try getting the token this way:
1. Open `discord.com/app` in your browser
2. Open DevTools page (`F12`) and select `Network` tab
3. Type `/api` in the `Filter` field
4. Select any successfull request
5. Open `Headers` tab
6. Copy your token in the `authorization` field
![image](https://user-images.githubusercontent.com/46501450/169656101-d54c470d-237e-4265-b002-4a269c2434c4.png)

Let me know if this works, and I will update the guide.
@Klaex @TsunamiHD

**Comment by Klaex** [comment]
If I paste the correct token the app tells me my token is invalid and will not save it nor try making a connection with it. I think the algorithm that tries to identify correct tokens is broken. 

The log above was made by removing characters from my correct token until the app said it was a valid token, so I got the error code 4004 because of that.

**Comment by Klaex** [comment]
```
XXXXXXXXXXXXXXXXXXXXXXXX.X--XXX.XXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXX-XXXXX-XXXXXXXXXXXXX
```

I generated two tokens and it seems that the only consistent pattern between them is the 24 characters at the start and the total length. My tokens seem to be 70 characters in length but the app expects 59. 

https://github.com/tangenx/lfdi/blob/e16957aff1744b9e4bead859c0c3a23e9c1a039c/lib/components/discord_form.dart#L83

I actually think I'm having a separate issue than the one the original poster is having, sorry for that

**Comment by tangenx** [comment]
Okay, I didn't know that the length of the token could be different. I'll fix that.

**Comment by tangenx** [comment]
Check out the [latest release](https://github.com/tangenx/lfdi/releases/tag/1.0.0-beta.8)
In addition to the validation, I also changed the token checking

**Comment by tangenx** [comment]
Closed due to inactivity
